version: 2.1

orbs:
  mvxt-test:
    jobs:
      test-env-interp:
        description: "Testing whether it's possible to interpolate params into env vars"
        docker:
          - image: bash:4.4.19
        environment:
          TEST_VAR_ONE: << parameters.test-var-one >>
          TEST_VAR_TWO: ${<< parameters.test-var-two >>}
        parameters:
          test-var-one:
            description: "Test var one"
            type: string
          test-var-two:
            description: "Test var two"
            type: string
        steps:
          - checkout
          - run:
              command: |
                echo "Echoing TEST_VAR_ONE: $TEST_VAR_ONE"
          - run:
              command: |
                echo "Echoing TEST_VAR_TWO: $TEST_VAR_TWO"
          - run: sh blah.sh

jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: echo $TEST_VAR
      - run:
          command: echo "test_var=$TEST_VAR"
      - run:
          command: |
            cat test.sh
            ./test.sh
  mac-test:
    macos:
      xcode: "11.3.0"
    steps:
      - checkout
      - run: which java
  executor-param-test:
    parameters:
      image:
        description: "Docker image to use"
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - run: echo "Hello, world!"
  docker-commands-test:
    docker:
      - image: cimg/base:stable
      - image: mikeyvxt/circleci-demo-backend 
        name: "backend"
    steps:
      - run: sleep 5
      - run: ssh root@localhost:8080 ls -al

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - mvxt-test/test-env-interp:
          test-var-one: "String1"
          test-var-two: "String2"
      - test:
          context: mvxt-prod
      - mac-test
      - executor-param-test:
          image: "circleci/node:10.15.1"
      - executor-param-test:
          image: "circleci/golang:1.12.4"
      - docker-commands-test

