version: 2.1

#############
# Inline Orb
#############
orbs:
  mvxt-test:
    jobs:
      test-env-interp:
        description: "Testing whether it's possible to interpolate params into env vars"
        docker:
          - image: bash:4.4.19
        environment:
          TEST_VAR_ONE: << parameters.test-var-one >>
        parameters:
          test-var-one:
            description: "Test var one"
            type: string
          test-var-two:
            description: "Test var two"
            type: string
        steps:
          - checkout
          - run:
              command: |
                echo "Echoing parameter interpolated as part of ENV config: $TEST_VAR_ONE"
          - run:
              command: |
                echo "Echoing parameter interpolated into actual run step: << parameters.test-var-two >>"
          - run: sh blah.sh

############
# Workflows
############
workflows:
  version: 2.1
  build-deploy:
    jobs:
      - mvxt-test/test-env-interp:
          test-var-one: "String1"
          test-var-two: "String2"
      - test:
          context: mvxt-prod
      - executor-param-test:
          name: test-node-job
          image: "circleci/node:10.15.1"
      - executor-param-test:
          name: test-go-job
          image: "circleci/golang:1.12.4"

##################
# Job Definitions
##################
jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: echo $TEST_VAR
      - run:
          command: echo "test_var=$TEST_VAR"
      - run:
          command: |
            cat test.sh
            ./test.sh
  executor-param-test:
    parameters:
      image:
        description: "Docker image to use"
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - run: echo "Hello, world!"

